### ISSUE TITLE
代码训练的权重怎么使用

### ISSUE THREAD

**Issue by caocheng1cc** [matthewsilk/CMRnet#3]
我在复现您的代码-CMRNet时，我训练30次都到权重文件 checkpoint.tar.但是我将他用于评估时发现，他会报错一下问题。我打开您开始上传的文件，发现他会报同样的错误，请问时什么原因导致的呢？

<img width="893" alt="1668424542233" src="https://user-images.githubusercontent.com/75966967/201646634-208853d4-ca9a-435a-a70b-a7aead8b063c.png">
<img width="416" alt="1668424582289" src="https://user-images.githubusercontent.com/75966967/201646756-fbfcba77-cc0c-4934-947d-c804c410b6c7.png">

**Comment by matthewsilk** [comment]
This is not an issue with the CMRnet R package

**Comment by caocheng1cc** [comment]
> This is not an issue with the CMRnet R package
这是由于什么原因导致的，这是我训练出来的结果。wo我用您训练出来的权重遇到了同样的问题
<img width="449" alt="1668428767328" src="https://user-images.githubusercontent.com/75966967/201659707-389fecf7-a4b0-4525-8a97-b6d2edf06d1a.png">
<img width="1038" alt="1668428893843" src="https://user-images.githubusercontent.com/75966967/201660054-87e04edf-245f-4cbb-97f0-e7b362224323.png">

**Comment by matthewsilk** [comment]
The screenshots provided here are for CMRNet in python. This is a GitGub repository for an R package with a similar name

**Comment by caocheng1cc** [comment]
> The screenshots provided here are for CMRNet in python. This is a GitGub repository for an R package with a similar name

我不能理解您说的什么意思，能详细说明嘛？

**Comment by duchengyao** [comment]
@caocheng1cc 他让你去下面那个链接，用英语问。

https://github.com/cattaneod/CMRNet
